<?xml version="1.0" encoding="UTF-8"?>
<definitions
	name="SapoBroker"
	targetNamespace="http://services.sapo.pt/broker"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://services.sapo.pt/broker"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl">
	
	<types>
		<xsd:schema elementFormDefault="qualified" targetNamespace="http://services.sapo.pt/broker">

			<xsd:complexType name="BrokerMessage">
				<xsd:all>
					<xsd:element name="MessageId" type="xsd:string" />
					<xsd:element name="Timestamp" type="xsd:string" />
					<xsd:element name="Expiration" type="xsd:string" />
					<xsd:element minOccurs="1" maxOccurs="1" name="DestinationName" type="xsd:string" />
					<xsd:element minOccurs="1" maxOccurs="1" name="TextPayload" type="xsd:string" />
				</xsd:all>
			</xsd:complexType>

			<xsd:element name="Publish">
				<xsd:complexType>
					<xsd:all>
						<xsd:element name="BrokerMessage" type="tns:BrokerMessage" />
					</xsd:all>
				</xsd:complexType>
			</xsd:element>

			<xsd:element name="Enqueue">
				<xsd:complexType>
					<xsd:all>
						<xsd:element name="BrokerMessage" type="tns:BrokerMessage" />
					</xsd:all>
				</xsd:complexType>
			</xsd:element>

			<xsd:element name="PublishResponse">
				<xsd:complexType />
			</xsd:element>

			<xsd:element name="EnqueueResponse">
				<xsd:complexType />
			</xsd:element>

		</xsd:schema>
	</types>

	<message name="PublishSoapIn">
		<part name="parameters" element="tns:Publish" />
	</message>

	<message name="PublishSoapOut">
		<part name="parameters" element="tns:PublishResponse" />
	</message>

	<message name="EnqueueSoapIn">
		<part name="parameters" element="tns:Enqueue" />
	</message>

	<message name="EnqueueSoapOut">
		<part name="parameters" element="tns:EnqueueResponse" />
	</message>

	<portType name="BrokerSoap">

		<operation name="Publish">
			<input message="tns:PublishSoapIn" />
			<output message="tns:PublishSoapOut" />
		</operation>

		<operation name="Enqueue">
			<input message="tns:EnqueueSoapIn" />
			<output message="tns:EnqueueSoapOut" />
		</operation>

	</portType>

	<binding name="BrokerSoap" type="tns:BrokerSoap">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
		<wsaw:UsingAddressing required="false" />

		<operation name="Publish">
			<soap:operation soapAction="http://services.sapo.pt/broker/publish" style="document" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>

		<operation name="Enqueue">
			<soap:operation soapAction="http://services.sapo.pt/broker/enqueue" style="document" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>

	</binding>

	<service name="Broker">
		<port name="BrokerSoap" binding="tns:BrokerSoap">
			<soap:address location="http://localhost:3380/broker/producer" />
		</port>
	</service>

</definitions>
