//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.28 at 09:01:34 AM WEST 
//


package pt.com.gcs.conf;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pt.com.gcs.conf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pt.com.gcs.conf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Config.Messaging.Dropbox }
     * 
     */
    public Config.Messaging.Dropbox createConfigMessagingDropbox() {
        return new Config.Messaging.Dropbox();
    }

    /**
     * Create an instance of {@link Config.Net }
     * 
     */
    public Config.Net createConfigNet() {
        return new Config.Net();
    }

    /**
     * Create an instance of {@link Config.Persistency }
     * 
     */
    public Config.Persistency createConfigPersistency() {
        return new Config.Persistency();
    }

    /**
     * Create an instance of {@link Config.Statistics }
     * 
     */
    public Config.Statistics createConfigStatistics() {
        return new Config.Statistics();
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link Config.Messaging }
     * 
     */
    public Config.Messaging createConfigMessaging() {
        return new Config.Messaging();
    }

}
