---
name: POE-Component-MantaTCP
version: 0.009000
author:
  - 'Pedro Melo <melo@co.sapo.pt>'
abstract: POE Interface to MantaTCP
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE: 0
  POE::Component::Client::TCP: 0
  POE::Filter::Block: 0
  Test::More: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
  version: 0
provides:
  POE::Component::MantaTCP:
    file: lib/POE/Component/MantaTCP.pm
    version: 0.009000
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
