
all:
	aclocal -I config
	autoheader
	automake --foreign --add-missing --copy
	autoconf

clean:
	rm -rf config.h.in configure Makefile.in autom4te.cache aclocal.m4 stamp-h.in src/Makefile.in test/Makefile.in 
